- platform: statistics
  name: "Total Energy Use (Hourly Max)"
  entity_id: sensor.total_energy_use_hourly
  state_characteristic: value_max
  max_age:
    hours: 1
  sampling_size: 360

- platform: statistics
  name: "Total Energy Use (Daily Max)"
  entity_id: sensor.total_energy_use_daily
  state_characteristic: value_max
  max_age:
    hours: 168
  sampling_size: 1008

- platform: group
  name: Power Consumption All Phases
  type: sum
  entities:
    - sensor.electricity_meter_power_consumption_phase_l1
    - sensor.electricity_meter_power_consumption_phase_l2
    - sensor.electricity_meter_power_consumption_phase_l3

- platform: group
  name: Smart Plug All Values
  type: sum
  entities:
    - sensor.smart_plug_1_power
    - sensor.smart_plug_2_power
    - sensor.smart_plug_3_power
    - sensor.smart_plug_4_power

- platform: integration
  source: sensor.smart_plug_1_power
  name: Smart Plug 1 Energy
  unit_prefix: k
  round: 2
  max_sub_interval:
    minutes: 5

- platform: integration
  source: sensor.smart_plug_2_power
  name: Smart Plug 2 Energy
  unit_prefix: k
  round: 2
  max_sub_interval:
    minutes: 5

- platform: integration
  source: sensor.smart_plug_3_power
  name: Smart Plug 3 Energy
  unit_prefix: k
  round: 2
  max_sub_interval:
    minutes: 5

- platform: integration
  source: sensor.smart_plug_4_power
  name: Smart Plug 4 Energy
  unit_prefix: k
  round: 2
  max_sub_interval:
    minutes: 5