- sensor:
  - name: All Lights Total Energy
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: measurement        
    state: "{{ 
        states('sensor.kitchen_energy_daily') | float(0) 
      + states('sensor.daily_shellyplusrgbwpm_b0a7324114a8_energy') | float(0)
      + states('sensor.tv_corner_energy_daily') | float(0)
      + states('sensor.toilet_first_floor_1_energy_daily') | float(0)
      + states('sensor.toilet_first_floor_2_energy_daily') | float(0)
      + states('sensor.toilet_downstairs_energy_daily') | float(0)
      + states('sensor.play_corner_energy_daily') | float(0)
      + states('sensor.pccorner1_energy_daily') | float(0)
      + states('sensor.pccorner2_energy_daily') | float(0)
      + states('sensor.pccorner3_energy_daily') | float(0)
      + states('sensor.master_bedroom_energy_daily') | float(0)
      + states('sensor.kitchen_energy_daily') | float(0)
      + states('sensor.home_office_energy_daily') | float(0)
      + states('sensor.hobby_room_energy_daily') | float(0)
      + states('sensor.dinner_corner_energy_daily') | float(0)
      + states('sensor.bed_side_lamp_tom_energy_daily') | float(0)
      + states('sensor.bed_side_lamp_1_energy_daily') | float(0)
      }}"

  - name: All Media Total Energy
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: measurement        
    state: "{{ 
        states('sensor.study_speaker_energy_daily') | float(0)
      + states('sensor.living_room_speaker_energy_daily') | float(0)
      }}"

  - name: All Climate Total Energy
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: measurement        
    state: "{{ 
        states('sensor.home_office_shutter_energy_daily') | float(0)
      + states('sensor.hobby_room_shutter_energy_daily') | float(0)
      }}"

  - name: Total Energy Use
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: measurement        
    state: "{{ 
        states('sensor.electricity_meter_power_consumption') | float(0)
      - states('sensor.electricity_meter_power_production') | float(0)
      }}"

  - name: Total Energy Use (Daily)
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: measurement        
    state: "{{ 
        states('sensor.daily_energy_consumption_offpeak') | float(0)
      - states('sensor.daily_energy_production_offpeak') | float(0)
      + states('sensor.daily_energy_consumption_peak') | float(0)
      - states('sensor.daily_energy_production_peak') | float(0)
      }}"

  - name: Wind Force Text
    state: >
      {% set wind_force_text = states('sensor.wind_force') | float %}
      {% if wind_force_text | float<=1 %}Calm
      {% elif wind_force_text | float<=2 | float>1 %}Light Air
      {% elif wind_force_text | float<=3 | float>2 %}Light Breeze
      {% elif wind_force_text | float<=4 | float>3 %}Gentle Breeze
      {% elif wind_force_text | float<=5 | float>4 %}Moderate Breeze
      {% elif wind_force_text | float<=6 | float>5 %}Fresh Breeze
      {% elif wind_force_text | float<=7 | float>6 %}Strong Breeze
      {% elif wind_force_text | float<=8 | float>7 %}Near Gale
      {% elif wind_force_text | float<=9 | float>8 %}Gale
      {% elif wind_force_text | float<=10 | float>9 %}Strong Gale
      {% elif wind_force_text | float<=11 | float>10 %}Whole Gale
      {% elif wind_force_text | float<=12 | float>11 %}Storm Force
      {% elif wind_force_text | float<=13 | float>12 %}Hurricane Force
      {%- endif %}