daily_energy_tarif_1_rounded:
  name: Daily Energy Consumption (Offpeak)
  source: sensor.electricity_meter_energy_consumption_tarif_1
  cycle: daily

daily_energy_tarif_2_rounded:
  name: Daily Energy Consumption (Peak)
  source: sensor.electricity_meter_energy_consumption_tarif_2
  cycle: daily

daily_energy_production_1_rounded:
  name: Daily Energy Production (Offpeak)
  source: sensor.electricity_meter_energy_production_tarif_1
  cycle: daily

daily_energy_production_2_rounded:
  name: Daily Energy Production (Peak)
  source: sensor.electricity_meter_energy_production_tarif_2
  cycle: daily

daily_gas:
  source: sensor.gas_meter_gas_consumption
  name: Daily Gas
  cycle: daily

daily_water:
  source: sensor.hw_watermeter_19a35a_total_water_usage
  name: Daily Water
  cycle: daily

monthly_energy_tarif_1_rounded:
  source: sensor.electricity_meter_energy_consumption_tarif_1
  name: Monthly Energy (Offpeak)
  cycle: monthly

monthly_energy_tarif_2_rounded:
  source: sensor.electricity_meter_energy_consumption_tarif_2
  name: Monthly Energy (Peak)
  cycle: monthly

monthly_gas:
  source: sensor.gas_meter_gas_consumption
  name: Monthly Gas
  cycle: monthly

daily_shellyplusrgbwpm_b0a7324114a8_energy:
  name: Cupboard Light Energy (Daily)
  source: sensor.shellyplusrgbwpm_b0a7324114a8_energy
  cycle: daily

home_office_shutter_energy_daily:
  name: Home Office Shutter Energy (Daily)
  source: sensor.home_office_shutter_energy
  cycle: daily

hobby_room_shutter_energy_daily:
  name: Hobby Room Shutter Energy (Daily)
  source: sensor.hobby_room_shutter_energy
  cycle: daily

total_energy_use_hourly:
  name: Total Energy Use (Hourly)
  source: sensor.total_energy_use_daily
  cycle: hourly

smart_plug_1_electricity_daily:
  name: Smart Plug 1 Electricity (Daily)
  source: sensor.smart_plug_1_energy
  cycle: daily

smart_plug_2_electricity_daily:
  name: Smart Plug 2 Electricity (Daily)
  source: sensor.smart_plug_2_energy
  cycle: daily

smart_plug_3_electricity_daily:
  name: Smart Plug 3 Electricity (Daily)
  source: sensor.smart_plug_3_energy
  cycle: daily

smart_plug_4_electricity_daily:
  name: Smart Plug 4 Electricity (Daily)
  source: sensor.smart_plug_4_energy
  cycle: daily