settings:
  variables:
    translate_unknown: Onbekend
    translate_idle: Inactief
    translate_home: Thuis
    translate_not_home: Niet thuis
    translate_availabe: Beschikbaar
    translate_no_updates: Geen updates
    translate_update_available: Update beschikbaar
    translate_updates_available: Updates beschikbaar
    translate_help: Tip, Dubbel klik voor meer info