title: Dashboard

views:
  - !include views/summary.yaml
  - !include views/energy.yaml
  - !include views/lights.yaml

button_card_templates: !include_dir_merge_named templates/button-card/
decluttering_templates: !include templates/decluttering-cards.yaml

background: >-
  linear-gradient(to bottom, rgba(var(--rgb-primary-color),.2),
  var(--primary-background-color))